server:
  port: 8080
  
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
        default-filters:
          - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: '*'
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: PBClient
          uri: lb://PBClient
          predicates:
            - Path=/app/micro/clients/**
        - id: PBRequest
          uri: lb://PBRequest
          predicates:
            - Path=/app/micro/requests/**
        - id: PBMyRequests
          uri: lb://PBMyRequests
          predicates:
            - Path=/app/micro/myrequests/**
        - id: PBEvaluation
          uri: lb://PBEvaluation
          predicates:
            - Path=/app/micro/evaluation/**
        - id: PBSimulation
          uri: lb://PBSimulation
          predicates:
            - Path=/app/micro/simulation/**