server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          default-label: main
          uri: https://github.com/Franciscoxd1123/tingeso3Cambios
          search-paths: config-data
  application:
    name: PBConfig